package EstadoAPP;

/**
* EstadoAPP/EstadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* lunes 28 de mayo de 2018 08:20:08 AM COT
*/

public final class EstadoHolder implements org.omg.CORBA.portable.Streamable
{
  public EstadoAPP.Estado value = null;

  public EstadoHolder ()
  {
  }

  public EstadoHolder (EstadoAPP.Estado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EstadoAPP.EstadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EstadoAPP.EstadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EstadoAPP.EstadoHelper.type ();
  }

}
