package EstadoAPP;


/**
* EstadoAPP/Estado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* lunes 28 de mayo de 2018 08:20:08 AM COT
*/

public interface Estado extends EstadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Estado
