package GeneroAPP;


/**
* GeneroAPP/GeneroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* lunes 28 de mayo de 2018 05:21:16 PM COT
*/

abstract public class GeneroHelper
{
  private static String  _id = "IDL:GeneroAPP/Genero:1.0";

  public static void insert (org.omg.CORBA.Any a, GeneroAPP.Genero that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GeneroAPP.Genero extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GeneroAPP.GeneroHelper.id (), "Genero");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GeneroAPP.Genero read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GeneroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GeneroAPP.Genero value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GeneroAPP.Genero narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GeneroAPP.Genero)
      return (GeneroAPP.Genero)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GeneroAPP._GeneroStub stub = new GeneroAPP._GeneroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GeneroAPP.Genero unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GeneroAPP.Genero)
      return (GeneroAPP.Genero)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GeneroAPP._GeneroStub stub = new GeneroAPP._GeneroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
