package GeneroAPP;

/**
* GeneroAPP/GeneroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* lunes 28 de mayo de 2018 05:21:16 PM COT
*/

public final class GeneroHolder implements org.omg.CORBA.portable.Streamable
{
  public GeneroAPP.Genero value = null;

  public GeneroHolder ()
  {
  }

  public GeneroHolder (GeneroAPP.Genero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GeneroAPP.GeneroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GeneroAPP.GeneroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GeneroAPP.GeneroHelper.type ();
  }

}
