package GeneroAPP;


/**
* GeneroAPP/GeneroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* lunes 28 de mayo de 2018 05:21:16 PM COT
*/

public interface GeneroOperations 
{
  boolean insertarGenero (int id, String nombre);
  String consultarGenero (int id);
  boolean eliminarGenero (int id);
  boolean actualizarGenero (int id, String nombre);
  String listarGenero ();
  void shutdown ();
} // interface GeneroOperations
