package GeneroAPP;


/**
* GeneroAPP/Genero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* lunes 28 de mayo de 2018 05:21:16 PM COT
*/

public interface Genero extends GeneroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Genero
