package PersonaAPP;


/**
* PersonaAPP/PersonaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* domingo 27 de mayo de 2018 01:49:32 PM COT
*/

abstract public class PersonaHelper
{
  private static String  _id = "IDL:PersonaAPP/Persona:1.0";

  public static void insert (org.omg.CORBA.Any a, PersonaAPP.Persona that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PersonaAPP.Persona extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PersonaAPP.PersonaHelper.id (), "Persona");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PersonaAPP.Persona read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PersonaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PersonaAPP.Persona value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PersonaAPP.Persona narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PersonaAPP.Persona)
      return (PersonaAPP.Persona)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PersonaAPP._PersonaStub stub = new PersonaAPP._PersonaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PersonaAPP.Persona unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PersonaAPP.Persona)
      return (PersonaAPP.Persona)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PersonaAPP._PersonaStub stub = new PersonaAPP._PersonaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
