package PersonaAPP;


/**
* PersonaAPP/Persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* domingo 27 de mayo de 2018 01:49:32 PM COT
*/

public interface Persona extends PersonaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Persona
