package PersonaAPP;


/**
* PersonaAPP/PersonaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* domingo 27 de mayo de 2018 01:49:32 PM COT
*/

public interface PersonaOperations 
{
  boolean insertarPersona (int identificacion, String nombre, String apellido, int edad, String genero, String estado);
  String consultarPersona (int identificacion);
  boolean eliminarPersona (int identificacion);
  boolean actualizarPersona (int identificacion, String nombre, String apellido, int edad, String genero, String estado);
  String listarPersona ();
  void shutdown ();
} // interface PersonaOperations
